import LegalPageLayout, { PolicySection, PolicyList } from './LegalPageLayout';


export default function PrivacyNotice() {
    return (
        <LegalPageLayout
            pageKey="privacy-policy"
            title="Privacy Policy"
            lastUpdated="September 18, 2026"
        >
            <PolicySection title="1. Introduction">
                <p>
                    The Mt. Masaraga Protected Landscape, under the stewardship of the
                    Protected Area Management Board (PAMB) and the Department of Environment
                    and Natural Resources (DENR), operates this booking and information
                    platform to manage ecotourism within the protected area.
                </p>
                <p>
                    This Privacy Policy explains what personal information we collect, how we
                    use and protect it, and the choices you have over your data. We are
                    committed to protecting your personal information in accordance with the
                    Data Privacy Act of 2012 (Republic Act No. 10173) and related rules
                    issued by the National Privacy Commission (NPC).
                </p>
                <p>
                    By using this platform to apply for permits, book trail dates, or
                    communicate with park staff, you agree to the practices described in this
                    policy.
                </p>
            </PolicySection>

            <PolicySection title="2. Information We Collect">
                <p>We collect the following categories of personal information:</p>
                <PolicyList
                    items={[
                        'Identity and contact details: full name, date of birth, valid government ID number, email address, and mobile number.',
                        'Permit and booking details: intended trail, number of members in your group, preferred date, and the booking reference generated by the system.',
                        'Emergency and safety information: emergency contact name and number, and health-related declarations you voluntarily provide for your own safety on the trail.',
                        'Payment information: payment method and reference numbers. We do not store full card numbers or payment credentials on our servers.',
                        'Technical information: your IP address, device type, browser type, and pages visited, collected through server logs and cookies, as described in our Cookie Policy.',
                    ]}
                />
            </PolicySection>

            <PolicySection title="3. How We Use Your Information">
                <p>Your information is used only for purposes directly related to protected area management:</p>
                <PolicyList
                    items={[
                        'To process permit applications and trail bookings, including payment confirmation.',
                        'To verify your identity at trailheads and for mandatory visitor registration under DENR guidelines.',
                        'To contact you regarding your booking, changes in trail conditions, or safety announcements.',
                        'To reach your emergency contact if you fail to check out or if an emergency is reported.',
                        'To compile visitor statistics needed for conservation planning and reporting, always in aggregate and de-identified form.',
                        'To respond to your inquiries through the help desk and contact pages.',
                    ]}
                />
                <p>
                    We do not sell, rent, or trade your personal information to third parties.
                </p>
            </PolicySection>

            <PolicySection title="4. Legal Basis for Processing">
                <p>
                    We process personal information on the following grounds: your consent,
                    which you may withdraw at any time by contacting us; the fulfillment of
                    legal obligations imposed on us as managers of a protected area, including
                    visitor registration and record keeping; and the protection of your vital
                    interests in the case of emergencies on the mountain.
                </p>
            </PolicySection>

            <PolicySection title="5. Sharing and Disclosure">
                <p>Your information may be shared in the following limited circumstances:</p>
                <PolicyList
                    items={[
                        'With authorized DENR and PAMB offices for permit validation, enforcement, and reporting.',
                        'With your emergency contact, search and rescue teams, or medical personnel in the event of an emergency.',
                        'With payment service providers (GCash, Maya, and Landbank) solely for processing the payment you initiated.',
                        'When required by law, subpoena, or government regulation.',
                    ]}
                />
                <p>
                    Any external party that receives your data is bound by confidentiality
                    obligations and processes data only for the purpose for which it was shared.
                </p>
            </PolicySection>

            <PolicySection title="6. Data Retention">
                <p>
                    Booking and permit records are retained for as long as your account is
                    active and for audit purposes after closure, in line with DENR record
                    keeping requirements. Emergency and safety declarations are kept only for
                    the duration of your trail activity and a reasonable period afterward for
                    incident reporting. Technical logs are retained no longer than necessary
                    for security and performance purposes.
                </p>
            </PolicySection>

            <PolicySection title="7. Data Security">
                <p>
                    We apply appropriate organizational and technical safeguards, including
                    encrypted transport of data, restricted access for trained staff only, and
                    routine deletion of data that is no longer needed. While no system is
                    completely secure, we work to protect your information against accidental
                    or unlawful destruction, loss, alteration, and unauthorized disclosure.
                </p>
            </PolicySection>

            <PolicySection title="8. Your Rights">
                <p>Under the Data Privacy Act, you have the right to:</p>
                <PolicyList
                    items={[
                        'Be informed whether your personal information is being processed and how.',
                        'Request access to the personal information we hold about you.',
                        'Request correction of inaccurate or incomplete information.',
                        'Request deletion or blocking of your data, subject to legal retention requirements.',
                        'Object to processing and, where applicable, request data portability.',
                        'File a complaint with the National Privacy Commission if you believe your rights have been violated.',
                    ]}
                />
            </PolicySection>

            <PolicySection title="9. Contact Us">
                <p>For any privacy concern, request, or complaint, contact:</p>
                <PolicyList
                    items={[
                        'Data Protection Officer, Mt. Masaraga Protected Landscape, DENR/PAMB Local Office, Ligao City, Albay.',
                        'Email: support@masaraga.gov.ph',
                        'You may also reach the National Privacy Commission at https://privacy.gov.ph for complaints.',
                    ]}
                />
            </PolicySection>

            <PolicySection title="10. Changes to This Policy">
                <p>
                    We may update this Privacy Policy from time to time. Changes will be
                    posted on this page with a revised "Last updated" date. Continued use of
                    the platform after changes take effect constitutes acceptance of the
                    updated policy.
                </p>
            </PolicySection>
        </LegalPageLayout>
    );
}